name: ci

on:
  push:
    branches:
      - 'feature/ci'
      - '!master'
      - '!develp'
      - '!develp/*'
      - '!fix/*'
      - '!fixes/*'
jobs:
  connect-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      
      - name: Configure Git
        run: |
          git config --global user.name 'CI Robot'
          git config --global user.email '111610370+4-ci-robot@users.noreply.github.com'

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY_ROBOT }}
          # fingerprint: ${  { secrets.SIGN_KEY_ROBOT }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      # - name: Update
      #   shell: bash
      #   run: .github/workflows/test.sh
      #   env:
      #     TERM: xterm-256color

      - name: Create Pull Request branch
        run: |
          echo ${GITHUB_SHA} > report.txt
          git add -A && curl whatthecommit.com/index.txt | git commit -F -
          git checkout -b feature/ci-pull-request

      # Note that will fail if branch already exists. 
      - name: Push Git Branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: feature/ci-pull-request

      # Note that will silently fail if PR already exists.
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: feature/ci-pull-request
          destination_branch: feature/ci
          pr_title: "Add/Update report.txt file"
          pr_body: "Automatically created from CI workflow."
          pr_reviewer: "romdhanisam"
          pr_assignee: "romdhanisam"
          pr_label: "test" 